// src/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";

// **IMPORT CORRETO** usando caminho relativo até src/components/ui
import SidebarWrapper from "../components/ui/SidebarWrapper";

export const metadata: Metadata = {
  title: "Sphere",
  description: "Generated by Sphere app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <body className="flex h-screen overflow-hidden">
        {/* side‐bar condicionada nas páginas de login/register */}
        <SidebarWrapper />

        {/* conteúdo principal */}
        <main className="flex-1 overflow-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
